wandb_version: 1

learning_rate:
  desc: null
  value: 0.02
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: CIFAR-100
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    code_path: code/models/nca/trainer_nca.py
    python_version: 3.8.16
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696882547.232601
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 77
      2:
      - 1
      - 41
      - 49
      - 55
      - 77
      3:
      - 13
      - 16
      - 23
      4: 3.8.16
      5: 0.15.12
      8:
      - 5
      13: darwin-arm64
