simulation_metadata:
    num_episodes: 150000
    num_steps_per_episode: 5
    num_substeps_per_step: 1
    w: 48
    h: 48
    n_channels: 16
    batch_size: 8
    hidden_size: 128
    device: "cuda:3"
    fire_rate: 0.5
    angle: 0.0
    learning_params:
        lr: 2e-3
        betas:
            - 0.5
            - 0.5
        lr_gamma:  0.9999
        model_path: "saved_model.pth"
    angle_chn: 0
    chn: 16
    scalar_chn: 16
    update_rate: 0.5
    # ['circle','lizard', 'heart', 'smiley', 'lollipop', 'unicorn', 'spiderweb']
    target: "heart"
    # ['noaux', 'binary', 'minimal', 'extended']
    aux_l_type: "binary"
    # ['laplacian', 'lap6', 'lap_gradnorm', 'steerable', 'gradient', 'steerable_nolap']
    model_type: laplacian
    mirror: False
    alive_threshold_value: 0.1
    pool_size : 128
    hex_grid : False
    

state:
    environment: null
    agents:
        automata:
            number: ${multiply:${simulation_metadata.w},${simulation_metadata.h}} #5184
            properties:
                cell_state:
                    name: "cell_state"
                    learnable: True
                    shape:
                        - ${state.agents.automata.number}
                        - ${simulation_metadata.n_channels}
                    initialization_function:
                        generator: "nca_initialize_state_pool"
                        arguments:
                            n_channels:
                                name: n_channels
                                shape:
                                - 1
                                initialization_function: null
                                learnable: false
                                dtype: int
                                value: 16
                            batch_size:
                                name: batch_size
                                shape:
                                - 1
                                initialization_function: null
                                learnable: false
                                dtype: int
                                value: 8
                            device:
                                name: device
                                shape:
                                - 1
                                initialization_function: null
                                learnable: false
                                dtype: str
                                value: ${simulation_metadata.device}
                            angle:
                                name: angle
                                shape:
                                - 1
                                initialization_function: null
                                learnable: false
                                dtype: float
                                value: 0.0
                            seed_size:
                                name: seed_size
                                shape:
                                - 1
                                initialization_function: null
                                learnable: false
                                dtype: int
                                value: 1
                            pool_size:
                                name: pool_size
                                shape:
                                - 1
                                initialization_function: null
                                learnable: false
                                dtype: int
                                value: ${simulation_metadata.pool_size}
                            scalar_chn:
                                name: scalar_chn
                                shape:
                                - 1
                                initialization_function: null
                                learnable: false
                                dtype: int
                                value: 16
                            chn:
                                name: chn
                                shape:
                                - 1
                                initialization_function: null
                                learnable: false
                                value: 16
                                dtype: int
                            w:
                                name: w
                                shape:
                                - 1
                                initialization_function: null
                                learnable: false
                                value: 48
                                dtype: int 
                            h:
                                name: h
                                shape:
                                - 1
                                initialization_function: null
                                learnable: false
                                value: 48
                                dtype: int    
                    dtype: "float"  
                    
    objects: null
    network:
        agent_agent:
            evolution_network:
                type: "grid_network"
                arguments:
                    shape:
                        - ${simulation_metadata.w} #72
                        - ${simulation_metadata.h} #72
        agent_object: null
        object_object: null
substeps:
    "0":
        name: "Evolution"
        description: "All automata cell states evolve by one step"
        active_agents:
            - "automata"
        observation:
            automata:
                ObserveAliveState:               
                    generator: "ObserveAliveState"
                    arguments: null
                    input_variables:
                            cell_state: "agents/automata/cell_state"
                    output_variables:
                            - AliveState
                
                ObserveNeighborsState:               
                    generator: "ObserveNeighborsState"
                    arguments: null
                    input_variables:
                            cell_state: "agents/automata/cell_state"
                    output_variables:
                            - NeighborsState
                        
        policy:
            automata:
                GenerateAliveMask:                
                    generator: "GenerateAliveMask"
                    arguments: null
                    input_variables:
                            cell_state: "agents/automata/cell_state"
                    output_variables:
                            - AliveMask
                
                GenerateStateVector:                
                    generator: "GenerateStateVector"
                    arguments: null
                    input_variables:
                            observation_grid : "NeighborsState"
                            cell_state: "agents/automata/cell_state"
                    output_variables:
                            - StateVector
        transition:
            IsoNCAEvolve:
                generator: "IsoNCAEvolve"
                arguments: null
                input_variables:
                    AliveMask: "AliveMask"
                    cell_state: "agents/automata/cell_state"
                output_variables:
                    - cell_state
            # NCAEvolve:
            #     generator: "NCAEvolve"
            #     arguments: null
            #     input_variables:
            #         cell_state: "agents/automata/cell_state"
            #     output_variables:
            #         - cell_state
        reward: null