simulation_metadata:
  num_episodes: 3
  num_steps_per_episode: 20
  num_substeps_per_step: 1
  h: 72
  w: 72
  n_channels: 16
  batch_size: 8
  device: mps
  hidden_size: 128
  fire_rate: 0.5
  angle: 128
  learning_params:
    lr: 0.002
    betas:
    - 0.5
    - 0.5
    lr_gamma: 0.9999
    model_path: saved_model.pth
  seed_size: 1
  pool_size: 128
  scalar_chn: 128
  chn: 128
state:
  environment: {}
  agents:
    automata:
      number: 5184
      properties:
        cell_state:
          name: cell_state
          shape:
          - 16
          - 5184
          initialization_function:
            generator: nca_initialize_state_pool
            arguments:
              n_channels:
                name: n_channels
                shape:
                - 1
                initialization_function: null
                learnable: false
                dtype: int
                value: 16
              batch_size:
                name: batch_size
                shape:
                - 1
                initialization_function: null
                learnable: false
                dtype: int
                value: 8
              angle:
                name: angle
                shape:
                - 1
                initialization_function: null
                learnable: false
                dtype: float
                value: 128
              seed_size:
                name: seed_size
                shape:
                - 1
                initialization_function: null
                learnable: false
                dtype: int
                value: 1
              pool_size:
                name: pool_size
                shape:
                - 1
                initialization_function: null
                learnable: false
                dtype: int
                value: 128
              scalar_chn:
                name: scalar_chn
                shape:
                - 1
                initialization_function: null
                learnable: false
                dtype: int
                value: 128
              chn:
                name: chn
                shape:
                - 1
                initialization_function: null
                learnable: false
                dtype: int
                value: 128
              device:
                name: device
                shape:
                - 1
                initialization_function: null
                learnable: false
                dtype: str
                value: mps
          learnable: true
          dtype: float
  objects: {}
  network:
    agent_agent:
      evolution_network:
        type: grid_network
        arguments:
          shape:
          - 72
          - 72
substeps:
  '0':
    name: Evolution
    active_agents:
    - automata
    observation:
    - generator: ObserveAliveState
      input_variables:
        cell_state: agents/automata/cell_state
      output_variables:
      - AliveState
      arguments: null
    - generator: ObserveNeighborsState
      input_variables:
        cell_state: agents/automata/cell_state
      output_variables:
      - NeighborsState
      arguments: null
    policy:
    - generator: GenerateStateVector
      input_variables:
        cell_state: agents/automata/cell_state
      output_variables:
      - StateVector
      arguments: null
    - generator: GenerateAliveMask
      input_variables:
        cell_state: agents/automata/cell_state
      output_variables:
      - AliveMask
      arguments: null
    transition:
    - generator: IsoNCAEvolve
      input_variables:
        cell_state: agents/automata/cell_state
      output_variables:
      - cell_state
      arguments: null
