simulation_metadata:
    num_episodes: 1000
    num_steps_per_episode: 20
    num_substeps_per_step: 1
    w: 72
    h: 72
    n_channels: 16
    batch_size: 8
    hidden_size: 128
    device: "cpu"
    fire_rate: 0.5
    angle: 0.0
    learning_params:
        lr: 2e-3
        betas:
            - 0.5
            - 0.5
        lr_gamma:  0.9999
        model_path: "saved_model.pth"
    angle_chn: 0
    chn: 16
    update_rate: 0.5
    # ['circle','lizard', 'heart', 'smiley', 'lollipop', 'unicorn', 'spiderweb']
    target: "lizard"
    # ['noaux', 'binary', 'minimal', 'extended']
    aux_l_type: "binary"
    # ['laplacian', 'lap6', 'lap_gradnorm', 'steerable', 'gradient', 'steerable_nolap']
    model_type: steerable
    mirror: False
    alive_threshold_value: 0.1
    

state:
    environment: null
    agents:
        automata:
            number: ${multiply:${simulation_metadata.w},${simulation_metadata.h}} #5184
            properties:
                cell_state:
                    name: "cell_state"
                    learnable: True
                    shape:
                        - ${state.agents.automata.number}
                        - ${simulation_metadata.n_channels}
                    initialization_function:
                        generator: "nca_initialize_state"
                        arguments:
                            n_channels: 
                                name: "n_channels"
                                learnable: False
                                shape:
                                    - 1
                                initialization_function: null
                                value: ${simulation_metadata.n_channels}
                                dtype: "int"
                            batch_size: 
                                name: "batch_size"
                                learnable: False
                                shape:
                                    - 1
                                initialization_function: null
                                value: ${simulation_metadata.batch_size}
                                dtype: "int"
                            device: 
                                name: "device"
                                learnable: False
                                shape:
                                    - 1
                                initialization_function: null
                                value: ${simulation_metadata.device}
                                dtype: "str"
                    dtype: "float"   
    objects: null
    network:
        agent_agent:
            evolution_network:
                type: "grid"
                arguments:
                    shape:
                        - ${simulation_metadata.w} #72
                        - ${simulation_metadata.h} #72
        agent_object: null
        object_object: null
substeps:
    "0":
        name: "Evolution"
        description: "All automata cell states evolve by one step"
        active_agents:
            - "automata"
        observation:
            automata:
                ObserveAliveState:               
                    generator: "ObserveAliveState"
                    arguments: null
                    input_variables:
                            cell_state: "agents/automata/cell_state"
                    output_variables:
                            - AliveState
                
                ObserveNeighborsState:               
                    generator: "ObserveNeighborsState"
                    arguments: null
                    input_variables:
                            cell_state: "agents/automata/cell_state"
                    output_variables:
                            - NeighborsState
                        
        policy:
            automata:
                GenerateAliveMask:                
                    generator: "GenerateAliveMask"
                    arguments: null
                    input_variables:
                            cell_state: "agents/automata/cell_state"
                    output_variables:
                            - AliveMask
                
                GenerateStateVector:                
                    generator: "GenerateStateVector"
                    arguments: null
                    input_variables:
                            observation_grid : "NeighborsState"
                            cell_state: "agents/automata/cell_state"
                    output_variables:
                            - StateVector
        transition:
            IsoNCAEvolve:
                generator: "IsoNCAEvolve"
                arguments: null
                input_variables:
                    AliveMask: "AliveMask"
                    cell_state: "agents/automata/cell_state"
                output_variables:
                    - cell_state
            # NCAEvolve:
            #     generator: "NCAEvolve"
            #     arguments: null
            #     input_variables:
            #         AliveMask: "AliveMask"
            #         cell_state: "agents/automata/cell_state"
            #     output_variables:
            #         - cell_state
        reward: null